# Builds and runs pytest on ubuntu-latest
# Tests python versions >=3.6
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  # https://github.com/actions/setup-python
  test-python3-ubuntu-latest:
    name: test py${{ matrix.python-version }} on linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    env:
      PYTHON: ${{ matrix.python-version }}
      OS: ubuntu

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install requirements
        run: pip install poetry && poetry install
      - name: run tests
        run: poetry run python -m pytest tests
